### ISSUE TITLE
trying to import umesh but can't

### ISSUE THREAD

**Issue by cachan3543** [Waffle1434/Blender-UE4-Importer#1]
getting this error
Python: Traceback (most recent call last):
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\UE4_importer\umesh.py", line 512, in execute
    if file.name != "": ImportUMeshAsObject(self.directory + file.name, materials=self.materials)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\UE4_importer\umesh.py", line 494, in ImportUMeshAsObject
    mesh = ImportMeshUAsset(filepath, uproject, materials, True)
  File "CAppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\UE4_importer\umesh.py", line 489, in ImportMeshUAsset
    case 'StaticMesh': return ImportStaticMesh(export, import_materials, log)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\UE4_importer\umesh.py", line 188, in ImportStaticMesh
    assert not cooked
AssertionError

is there a way to fix this/uncook the uassets?

**Comment by Waffle1434** [comment]
I'm not familiar enough with Unreal unfortunately to know if you can uncook, what assets are you trying to import?

**Comment by Yu-Sol** [comment]
Similar problem. I tried to import assets from PUBG (PC, UE 4.16), which I had previously pulled out with the umodel program

**Comment by Waffle1434** [comment]
Cooked assets aren't supported, you guys might have better luck with umodel. This addon is only really intended to work with a functioning Unreal Engine 4 project, and unfortunately I couldn't support every engine version.
